"""SessKit: read, parse, and export local coding-agent sessions."""

from __future__ import annotations

__version__ = "0.2.3"

from sesskit.activity import load_activity, to_v1_dicts
from sesskit.activity_reader import (
    ActivityReader,
    IncrementalUnsupported,
    PageResult,
    PiActivityReader,
    PollResult,
    open_activity_reader,
    supports_incremental,
)
from sesskit.activity_reader_jsonl import (
    ClaudeActivityReader,
    CodexActivityReader,
)
from sesskit.adapters import Capabilities, RuntimeAdapter, get_adapter, list_adapters
from sesskit.conformance import ConformanceReport, Violation, run_conformance
from sesskit.conversation import conversation_from_activity, project_session_conversation
from sesskit.errors import (
    classify_agent_error,
    classify_error,
    native_http_status,
    with_classification,
)
from sesskit.models import (
    ActivityEvent,
    ActivitySnapshot,
    AgentError,
    AssistantMessage,
    CompactionEvent,
    CompactionInfo,
    ConversationMessage,
    DecidedBy,
    ErrorEvent,
    ErrorKind,
    ErrorScope,
    Evidence,
    InteractionEvent,
    InteractionRequest,
    InvocationPairing,
    LifecycleEvent,
    MessageOrigin,
    RelationKind,
    SessionInfo,
    SessionOutcome,
    SessionRelation,
    Thinking,
    ToolCall,
    ToolInvocation,
    ToolResult,
    ToolResultOutcome,
    Turn,
    TurnOutcome,
    TypedEvent,
    Usage,
    UserMessage,
    as_typed,
    make_session_info,
    session_key,
    turn_id_for,
)
from sesskit.parsers.common import HostExtension
from sesskit.registry import ConversationLoadError, load_session_conversation
from sesskit.relations import claude_continuation_target, resolve_continuation, session_relations
from sesskit.transcript import SCHEMA_ID, count_events, load_events
from sesskit.turns import (
    derive_session_outcome,
    derive_turns,
    error_views,
    interaction_views,
    pair_invocations,
    with_turn_ids,
)
from sesskit.visibility import visible_in_conversation, visible_in_v1

__all__ = [
    "SCHEMA_ID",
    "ActivityEvent",
    "ActivityReader",
    "ActivitySnapshot",
    "AgentError",
    "AssistantMessage",
    "Capabilities",
    "ClaudeActivityReader",
    "CodexActivityReader",
    "CompactionEvent",
    "CompactionInfo",
    "ConformanceReport",
    "ConversationLoadError",
    "ConversationMessage",
    "DecidedBy",
    "ErrorEvent",
    "ErrorKind",
    "ErrorScope",
    "Evidence",
    "HostExtension",
    "IncrementalUnsupported",
    "InteractionEvent",
    "InteractionRequest",
    "InvocationPairing",
    "LifecycleEvent",
    "MessageOrigin",
    "PageResult",
    "PiActivityReader",
    "PollResult",
    "RelationKind",
    "RuntimeAdapter",
    "SessionInfo",
    "SessionOutcome",
    "SessionRelation",
    "Thinking",
    "ToolCall",
    "ToolInvocation",
    "ToolResult",
    "ToolResultOutcome",
    "Turn",
    "TurnOutcome",
    "TypedEvent",
    "Usage",
    "UserMessage",
    "Violation",
    "__version__",
    "as_typed",
    "classify_agent_error",
    "classify_error",
    "claude_continuation_target",
    "conversation_from_activity",
    "count_events",
    "derive_session_outcome",
    "derive_turns",
    "error_views",
    "get_adapter",
    "interaction_views",
    "list_adapters",
    "load_activity",
    "load_events",
    "load_session_conversation",
    "make_session_info",
    "native_http_status",
    "open_activity_reader",
    "pair_invocations",
    "project_session_conversation",
    "resolve_continuation",
    "run_conformance",
    "session_key",
    "session_relations",
    "supports_incremental",
    "to_v1_dicts",
    "turn_id_for",
    "visible_in_conversation",
    "visible_in_v1",
    "with_classification",
    "with_turn_ids",
]
